### ISSUE TITLE
Relative file references are not resolved outside of definitions

### ISSUE THREAD

**Issue by jebbench** [jfinkhaeuser/prance#1]
Within my JSON I have a $ref to a relative file path but when parsing get the error:
```
Exception caught: (<class 'swagger_spec_validator.common.SwaggerValidationError'>)

Exception message: unknown url type: ./schema/ChangePasswordEntity.json
```
Extract from swagger.json
```
{
    "in": "body",
    "name": "ChangePasswordEntity",
    "required": true,
    "schema": {
        "$ref": "./schema/ChangePasswordEntity.json"
    }
}
```
Code:
```
from prance import ResolvingParser
from prance.util import fs, formats

...

parser = ResolvingParser(file)
contents = formats.serialize_spec(parser.specification, filename)
fs.write_file(filename, contents)
```

**Comment by jebbench** [comment]
I've updated my swagger file to put the external reference in the definitions and it resolves correctly:
```
{
    "in": "body",
    "name": "ChangePasswordEntity",
    "required": true,
    "schema": {
        "$ref": "#/definitions/ChangePasswordEntity"
    }
}
...
"definitions": {
        "ChangePasswordEntity": {
            "$ref": "./schema/ChangePasswordEntity.json"
        },
}
```

**Comment by jfinkhaeuser** [comment]
Man, I did not see this issue. I'm very sorry about that!

I'll take that on as a new feature. It shouldn't be too hard to implement.

I'm not 100% sure that they *should* work that way. Unfortunately, the specifications are a little open to interpretation here.

[Swagger/OpenAPI](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md) itself doesn't specify much at all. [JSON Schema](http://json-schema.org/latest/json-schema-core.html#rfc.section.8) specifies relative references (`#` into `definitions`) and absolute references (URIs with fragment). [JSON Pointers](https://tools.ietf.org/html/rfc6901) do the same.

But relative path-like references as you describe wouldn't be too hard.

**Comment by jfinkhaeuser** [comment]
Your test case works now :)

**Comment by jfinkhaeuser** [comment]
@jebbench upgrade to v0.5.0

**Comment by jebbench** [comment]
Nice one; I won't get chance to test it this week but I should do next week - I'll report back.

Cheers.
