### ISSUE TITLE
Wrong validation messages because of version fallback with openapi 3.0

### ISSUE THREAD

**Issue by michalzubkowicz** [jfinkhaeuser/prance#20]
Currently this code: 
``

    from .util.exceptions import raise_from
    try:
      try:
        validate_v3_spec(self.specification)
        self.__set_version(BaseParser.SPEC_VERSION_3_PREFIX, spec_version)
      except TypeError as type_ex:  # pragma: nocover
        raise_from(ValidationError, type_ex)
      except JSEValidationError as v3_ex:
        try:
          validate_v2_spec(self.specification)
          self.__set_version(BaseParser.SPEC_VERSION_2_PREFIX, spec_version)
        except TypeError as type_ex:  # pragma: nocover
          raise_from(ValidationError, type_ex)
    except RefResolutionError as ref_ex:
      raise_from(ValidationError, ref_ex)

``

Produces wrong validation messages when there is an error in openapi schema 3.0.0
It returns openapi 2.0.0 messages instead of 3.0.0. After removing fallback correct error messages are shown. 
It should use fallback only when openapi version was not specified. I could produce patch, but I don't know what is your preferred way to solve this problem. This fallback is for a reason there? 

## Environment
- OS: Linux
- Python version:  3.6
- Swagger/OpenAPI version used: 3.0.0
- Backend: openapi-spec-validator

@jfinkhaeuser

**Comment by jfinkhaeuser** [comment]
Hmm. Thanks for this! Even with the @mention it got lost in my email, sorry about that.

Well, the idea is that we try v3 first, then try v2, and then fail as a way of detecting the version. But you're right, with an error in a v3 spec, the wrong message would be produced.

I'll produce a patch soon.

**Comment by jfinkhaeuser** [comment]
FWIW, I'm happy to accept PRs in general. But I can probably get a fix out tomorrow.

**Comment by michalzubkowicz** [comment]
You are fast, thanks ;)

**Comment by jfinkhaeuser** [comment]
The fix is basically done, but the builds fail for other reasons. I'll need a tad longer to get a release out. Should happen today, though!

**Comment by jfinkhaeuser** [comment]
v0.13.0 is released.

The fallback is no longer used; instead, the major spec version is used to determine the exact validation method.

Looking at the code again, it became obvious that the fallback is from a time before we parsed and examined the spec version - so now it's useless, and as you pointed out actually confusing.
