### ISSUE TITLE
Are local references not suppose to be resolved?

### ISSUE THREAD

**Issue by njharman** [jfinkhaeuser/prance#34]
## Expected Behaviour
Before I work on PR wanted to ask...

Local # references expanded. Instead of this 'paginator': {'$ref': '#/definitions/Paginator'}  I'd expect the {ref} dict to be replaced with the actual definition. Or am I just not understanding how this is suppose to work?

## Actual Behaviour
ERROR in "spec.yaml" [ResolutionError]: Recursion reached limit of 1 trying to resolve "file:///spect.yaml#/definitions/V1Fooer"!

## Environment
- OS: Apple/BSD
- Python version: 3.7.2
- Swagger/OpenAPI version used: 2.0
- Backend: (flex, swagger-spec-validator or openapi-spec-validator) flex 

@jfinkhaeuser

**Comment by jfinkhaeuser** [comment]
It'd be good to know more about the spec you're using this on.

By your description, I think you're expecting the right thing. In the example `petstore.yaml`, that works according to the test case at: https://github.com/jfinkhaeuser/prance/blob/bcff3eaed4f7ad4a9e419c73ee12016fd5ed5747/tests/test_resolving_parser.py#L46

Maybe there's something different in your schema?

**Comment by njharman** [comment]
Thanks for confirming. The spec is huge, complicated, and too full of business stuff can't post on internet. (and wrong somehow). I created a minimal example works as expected (I just wasn't sure what "expected was). I'll have to figure out what's wrong with my spec. It does validate with --no-resolve.  Maybe there's a circular ref or something like that.
