### ISSUE TITLE
ValidationError: expected string or bytes-like object

### ISSUE THREAD

**Issue by DeAJota** [jfinkhaeuser/prance#35]
I'm creating app with Flask, Connexion and Swagger. I want split swagger yaml file in multilpe files.
I have followed this reply:
https://github.com/zalando/connexion/issues/254#issuecomment-497194240

When I execute my app appears the exception. This exception is raised by the function _validate_openapi_spec_validator on class BaseParser, line 235.
`validate_v2_spec(self.specification)`
specification is a dict.

This is the yaml with the reference:

```
swagger: "2.0"

info:
  title: "Document Repository Service API"
  version: "1.0"

basePath: /v1.0

paths:
  $ref: ./resolutions.yaml
```

And this is the yaml referenced:
```
 /resolutions/{id}:
      get:
        x-swagger-router-controller: controllers.resolution_controller
        operationId: get_resolution
        parameters:
          - name: id
            in: path
            description: Resolution ID
            type: string
            required: true
          - name: format
            in: query
            type: string
            enum: [xml, json]
            required: false
            default: xml
          - name: encoding
            in: query
            type: string
            enum: [utf-8, original]
            required: false
            default: utf-8
        responses:
          200:
            description: OK
          404:
            description: A resolution with the specified ID was not found.

```

**Comment by jfinkhaeuser** [comment]
The reason is that JSON doesn't accept any keys that are not strings. Your YAML contains integer keys in the form of response codes. Make them strings by quoting them and it will be fine.

**Comment by jfinkhaeuser** [comment]
FWIW, this is documented in the readme - look for strict mode.

**Comment by DeAJota** [comment]
Excuse me for my mistake, I should have read more, you are absolutely right

**Comment by jfinkhaeuser** [comment]
No, it's all good, no need for excuses! Is there something about the documentation I could improve?

**Comment by DeAJota** [comment]
I think isn't necessary. I followed the yaml code examples of Swagger/OpenApi and, how you say, they does not always match the JSON specs. Thank you so much for your attention.

**Comment by adaamz** [comment]
Would be nice to know file+line of validation error, if you have multiple files/big files it's hard to find it.

Anyway your answer helped me, thx!

**Comment by jfinkhaeuser** [comment]
@adaamz yes, see #74 - when I get to it :)
