### ISSUE TITLE
Validation doesn't indicate error line in file when response code is not a string

### ISSUE THREAD

**Issue by cigano** [jfinkhaeuser/prance#36]
## Expected Behaviour

Given a YAML file which `paths.{path}.get.responses` has a response code expressed as a number, 
two things could happen:

 - The validation runs ok ([Connexion](https://github.com/zalando/connexion) accepts response codes as integers;
 - The validation fails, pointing the correct line that the error happened.

## Actual Behaviour

I have a message like this:

```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "server.py", line 21, in <module>
    app.add_api(get_bundled_specs(Path('specifications/openapi.yaml')))
  File "server.py", line 13, in get_bundled_specs
    parser.parse()
  File "/usr/local/lib/python3.5/dist-packages/prance/__init__.py", line 134, in parse
    self._validate()
  File "/usr/local/lib/python3.5/dist-packages/prance/__init__.py", line 275, in _validate
    BaseParser._validate(self)
  File "/usr/local/lib/python3.5/dist-packages/prance/__init__.py", line 172, in _validate
    validator(parsed)
  File "/usr/local/lib/python3.5/dist-packages/prance/__init__.py", line 225, in _validate_openapi_spec_validator
    raise_from(ValidationError, type_ex)
  File "<string>", line 5, in raise_from
prance.ValidationError: expected string or bytes-like object
```

This message is very misleading. For a long file, it took me a considerable amount of time to find the problem.

## Steps to Reproduce

Create a YAML file like this:

```
openapi: 3.0.0
info:
  description: My API
  version: "1.0.0"
  title: My Swagger API

paths:
  /people:
    get:
      operationId: controllers.people.read_all
      tags:
        - people
      summary: Retrieves people
      description: Retrieves people
      parameters:
        - name: length
          in: query
          schema:
            type: integer
          description: Number of people to get from database
          required: false
        - name: offset
          in: query
          schema:
            type: integer
          description: Offset from beginning of list where to start gathering people
          required: false
      responses:
        200:
          description: Successful
```

Make sure the response code is integer, not string.

## Environment
- OS: Ubuntu 14.06
- Python version: 3.7
- Swagger/OpenAPI version used: 3.0
- Backend: (flex, swagger-spec-validator or openapi-spec-validator): openapi-spec-validator

@jfinkhaeuser

**Comment by jfinkhaeuser** [comment]
I'm sort of aware, and will take a look. The problem is that the exceptions come from the underlying validation backend, and not all backends provide good information. But it's been on my mental list to improve this.

**Comment by jfinkhaeuser** [comment]
So upon further investigation, it turns out I can't fix that - that's an issue upstream in `openapi-spec-validator`. It comes down to it simply passing on the spec to a `jsonschema` validator, which expects only strings (i.e. tries to match with regexes).

Since it isn't valid behaviour to use integer keys anyway, I doubt you can convince either of the upstream maintainers to change it. For prance, the only thing that's coming up is a `TypeError` with the minimal information you're seeing, so there's not a lot of chance of extrapolating from there.

Nevertheless, I've made a few changes that at least point you in the right direction (strict mode vs. non-strict mode).
