### ISSUE TITLE
'ResolutionError: Cannot resolve reference'  when parse $ref which has '~1'

### ISSUE THREAD

**Issue by Lyangyangyang** [jfinkhaeuser/prance#38]
## Expected Behaviour
It is expected that the $ref which contains '~1' should be correctly parsed 

### Minimal Example Spec
**a.yaml**
```
paths:
  /api/v2/vms:
    $ref: ./b.yml#/paths/~1api~1v2~1vms
    ..........................
    other thing

```
**b.yaml**
```
paths:
  /api/v2/vms:
    get:
      operationId: list_vm
      description: get all 
      ............................
      other thing
```
## Actual Behaviour
raise ResolutionError: Cannot resolve reference actualy

## Steps to Reproduce

1. parse yaml which has $ref with '~1'

## Environment
- OS: linux
- Python version: 2.7
- Swagger/OpenAPI version used: 3.0.0
- Backend: openapi-spec-validator

@jfinkhaeuser

**Comment by Lyangyangyang** [comment]
@jfinkhaeuser ,   please help fix this issue ,thanks in advance.

**Comment by jfinkhaeuser** [comment]
I'll look into it - but it might be an issue with the backend. Either way, I'll let you know something ASAP.

**Comment by Lyangyangyang** [comment]
Thank you very much . It helps a lot

**Comment by DavidMeu** [comment]
After this fix I'm still having issues.
`- $ref: '#/paths/~1names~1%7Bname_id%7D/get/parameters/0'`

error:
`'Object at "/paths" does not contain key: /alerts/%7Balert_id%7D'`
