### ISSUE TITLE
endless loop when parse recursive  $ref 

### ISSUE THREAD

**Issue by Lyangyangyang** [jfinkhaeuser/prance#40]
## Expected Behaviour
parse with no errors 

### Minimal Example Spec
```
components:
  schemas:
    topo_info:
      type: object
      properties:
        id:
          type: string
          description: Topo ID
        name:
          type: string
          description: Topo name
        child_topos:
          type: array
          description: Child topo
          items:
            - $ref: '#/components/schemas/topo_info'
```
## Actual Behaviour
The parser falls to endless loop . I set recursive limit to 100 , it donot work .
```
File "/api_spec/prance/util/resolver.py", line 175, in _resolve_partial
    recursions)))
  File "/api_spec/prance/util/resolver.py", line 102, in _dereferencing_iterator
    ref_value = self.__reclimit_handler(self.__reclimit, ref_url)
  File "/api_spec/prance/util/resolver.py", line 16, in default_reclimit_handler
    'resolve "%s"!' % (limit, parsed_url.geturl()))
ResolutionError: Recursion reached limit of 100 trying to resolve file 
```
## Environment
- OS: linux
- Python version: 2.7
- Swagger/OpenAPI version used: 3
- Backend: openapi-spec-validator

@jfinkhaeuser

**Comment by jfinkhaeuser** [comment]
Thank you for this report.

Recursive references cannot be resolved - what would the result be?

**Comment by Lyangyangyang** [comment]
Thank you for your quick response .Actually I donnot know how to resolve ,but I need to get the spec of the yaml file . I am blocked by this kind of yaml file . Do you know how to get spec of this kind yaml file? @jfinkhaeuser

**Comment by jfinkhaeuser** [comment]
Well, it's invalid, and not resolvable. So whatever specs you get out of it won't be what you really need. You should be able to use the `BaseParser` class to get a decent approximation, though.

**Comment by jfinkhaeuser** [comment]
Failing that, just parse the YAML manually.

**Comment by jfinkhaeuser** [comment]
The merged PR should help with debugging at least.
