### ISSUE TITLE
Consider creating a changelog

### ISSUE THREAD

**Issue by pbasista** [jfinkhaeuser/prance#44]
Consider creating a changelog so that it would be possible to easily determine roughly which changes have been made between the released versions.

**Comment by jfinkhaeuser** [comment]
I'm lazy with changelogs - but you've got a point, of course!

**Comment by jfinkhaeuser** [comment]
There's a changelog now. It's pretty useless as yet, of course, but should help you in future. Thanks for pointing this out!
