### ISSUE TITLE
CLI tests test_convert_defaults and test_convert_output fail without network

### ISSUE THREAD

**Issue by jayvdb** [jfinkhaeuser/prance#46]
The CLI tests `test_convert_defaults` and `test_convert_output` fail without network.

In RPM packaging, all tests which require a network have to be disabled as the RPMs are built in an isolated VM to ensure they are reproducible.

As this two tests are verifying CLI behaviour, it would be a good idea if they didnt rely on the network.

**Comment by jfinkhaeuser** [comment]
Yes, I agree. But the conversion functionality is actually done with a web service. I can disable the tests under special conditions, I suppose.

Really, though, it'd be nice to have this functionality within the package. So far, funds for going through that effort have been sadly lacking :-/

I'll have a think about how best to tackle this.

**Comment by jayvdb** [comment]
Oh, if these cli functions depend on a network service, then disabling those tests is appropriate.

I wouldnt call it a bug ; sounds like a feature request.

**Comment by jfinkhaeuser** [comment]
Overly aggressive classification means it won't drop off my radar so easily ;)
