### ISSUE TITLE
deprecation warning about collections

### ISSUE THREAD

**Issue by jlipps** [jfinkhaeuser/prance#47]
## Expected Behaviour

No deprecation warnings produced when prance is used

### Minimal Example Spec

I use Prance in my OpenAPI / Connexion app like so

```py
def get_bundled_specs(main_file):
    parser = prance.ResolvingParser(str(main_file.absolute()), lazy=True, strict=True)
    parser.parse()
    return parser.specification
```

## Actual Behaviour

This deprecation warning is output:

```
<snip>/.venv/lib/python3.7/site-packages/prance/util/path.py:122: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
    if not isinstance(obj, collections.MutableMapping):  # pragma: nocover
```

## Steps to Reproduce

Simply run the app.

## Environment
- OS: macOS Mojave
- Python version: 3.7
- Swagger/OpenAPI version used: 3
- Backend: (flex, swagger-spec-validator or openapi-spec-validator) - no backend specified

@jfinkhaeuser

**Comment by jfinkhaeuser** [comment]
Thanks for this! I'll look into it ASAP.
