### ISSUE TITLE
SwaggerValidationError: expected string or buffer

### ISSUE THREAD

**Issue by ptman** [jfinkhaeuser/prance#9]
I get this error trying to do:

```python
from prance import ResolvingParser
p = ResolvingParser('swagger.yaml')
```

The yaml file is valid according to editor.swagger.io and http://bigstickcarpet.com/swagger-parser/www/index.html

I have no idea where in the swagger file the error is. A line number or similar would be helpful

**Comment by jfinkhaeuser** [comment]
Thanks for the report!

Yeah, I know a line number would be great. Ugh. I'll see what I can do about that. Do you have the file so I can reproduce? Or is that sensitive? You can email me directly at jens@finkhaeuser.de if you prefer.

What OS are you using? Can you post the full stack trace?

Thanks!

**Comment by jfinkhaeuser** [comment]
So, line numbers are going to be difficult. I'm doing two steps here, a) is read the file into a Python data structure (nested dicts/lists, etc.), and b) to validate the structure via swagger_spec_validator.

At the point you get a SwaggerValidationError, there are no more line numbers known. The best thing would be some kind of keyword context, but swagger_spec_validator does not provide that.

I'm a little reluctant re-implementing this part... but let's see what else I can find.

**Comment by ptman** [comment]
Right, a keyword would do just as fine.

**Comment by ptman** [comment]
traceback: https://gist.github.com/ptman/65a9e2c08218fae338a363c782e053bd

**Comment by jfinkhaeuser** [comment]
Thanks for this.

The TL;DR is, I'm going to replace the validation backend. That solves your issue, another issue, and you should get better error messages in case there's something weird in your spec :)

**Comment by jfinkhaeuser** [comment]
Took me a while to see the obvious: this is the same issue as #5.

Still, if it crops up many times, let's still use a different backend. I've made it so people can use the old backend, so that should not cause any issues.

**Comment by jfinkhaeuser** [comment]
0.8 should fix it. Otherwise, set strict = False :)
